apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: {{ .Chart.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        # force restarting the Pod once any config changes
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha1sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha1sum }}
        # force restarting the pod once the main branch changes
        forceUpgrade: "{{ now | unixEpoch }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
            - secretRef:
                name: {{ .Chart.Name }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 3
            httpGet:
              path: /{{ .Chart.Name }}/actuator/health/readiness
              port: {{ .Values.container.port }}
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 3
            httpGet:
              path: /{{ .Chart.Name }}/actuator/health/liveness
              port: {{ .Values.container.port }}