apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  zeebe.client.cloud.clientid: {{ .Values.camunda.cloud.clientId | b64enc }}
  zeebe.client.cloud.clientsecret: {{ .Values.camunda.cloud.clientSecret | b64enc }}
  zeebe.client.cloud.clusterid: {{ .Values.camunda.cloud.clusterId | b64enc }}